### PR TITLE
Chore: Add socials to footer of website

### PR DESCRIPTION
**Pull request by RakeshPotnuru**
Fixes: #9 

image

### CODE REVIEW

**Comment by PatelN123** [comment]
Hey @RakeshPotnuru are we able to add the socials onto the home page footer as well please?

**Comment by RakeshPotnuru** [comment]
Sure

**Comment by PatelN123** [comment]
I think under the Support Us category in the footer would be nice.

**Comment by RakeshPotnuru** [comment]
I saw chakra ui website. They added on top of vercel button.

**Comment by RakeshPotnuru** [comment]
@PatelN123

**Comment by PatelN123** [comment]
Looks good to me, thanks!

**Pull request merged**
