### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by KarlGusta**

### CODE REVIEW

**Comment by PatelN123** [comment]
Great work! Would it be possible to add the logo 3 from the folder onto the website?
If we can add the colours to logo 3 that'd be great.
Let me know your thoughts.

**Comment by KarlGusta** [comment]
Yeah. Logo 3 looks good. The only thing is the colors. Maybe we try it on the light mode only. I would add the colors but my graphic design is not that good.

**Comment by KarlGusta** [comment]
Viewing the two from the browser, you can see the Image and text of the light one is larger compared to the dark one. 
Take a look here:
1. Light mode: https://user-images.githubusercontent.com/33565767/174059231-d2978c74-cae3-4ef2-8b2a-5605917e971c.png
2. https://user-images.githubusercontent.com/33565767/174059149-be57495d-d039-41d3-bffe-e9bf3bdebdb3.png

**Comment by PatelN123** [comment]
Thanks for this. This is as I suspected.
Let's try the Light mode image on dark mode and light mode. I think it'll work, but let's give that a go.
Would you mind editing the PR?

**Comment by KarlGusta** [comment]
> I think that works great! Do you agree @KarlGusta?

Yes, it will. Great advice from your side.

**Comment by PatelN123** [comment]
Awesome, then we'll merge!

**Pull request merged**
