### PR TITLE
Fix: Canny load on every page

### PR DESCRIPTION
**Pull request by KarlGusta**
- Canny changelog to load on every page

### CODE REVIEW

**Comment by PatelN123** [comment]
Hi @KarlGusta,

This doesn't seem to work?
When I click this button, nothing happens.
image

**Comment by KarlGusta** [comment]
Hello Patel. I see it now. At first load, it doesn't work but on reloading the second time, it works. I have seen the documentation. componentDidMount() needs to be implemented so that when the page has finished loading, the SDK can then be called. Let me keep digging for the solution.

**Comment by PatelN123** [comment]
Thank you.

**Comment by PatelN123** [comment]
@KarlGusta This doesn't seem to work on iPad, could we fix up the old way that we had this set up?

**Comment by KarlGusta** [comment]
The old way is great. Still working on it. My findings so far:
1. For it to work on every page, the page needs to be refreshed after initial loading.
2. To do this without affecting the user, we need to use `useEffect` or `componentDidMount` to call the SDK as per the Canny docs.

**Comment by PatelN123** [comment]
This works great! Thank you @KarlGusta!

**Comment by KarlGusta** [comment]
> This works great! Thank you @KarlGusta!

Welcome.

**Pull request merged**
